{% set name = "rembg" %}
{% set version = "2.0.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rembg-{{ version }}.tar.gz
  sha256: 7d30e19997188d6bd78049228aefaca3508c36e07746c953a4b0215ca8cb5d2f
  patches:
    - cli.patch

build:
  entry_points:
    - rembg=rembg.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - setuptools >=65.5.1
    - wheel
  run:
    - aiohttp
    - asyncer
    - click
    - fastapi
    - filetype
    - gradio
    - jsonschema  # Imported but not in requirements
    - numpy
    - onnxruntime
    - opencv
    - pillow
    - pooch
    - pymatting
    - python >=3.8,<3.12
    - python-multipart  # Not imported
    - scikit-image  # Not imported
    - scipy
    - starlette  # Imported but not in requirements
    - tqdm
    - uvicorn
    - watchdog

test:
  imports:
    - cv2
    - rembg
  commands:
    - pip list
    # - pip check  # Fails due to opencv
    - rembg --help  # Added patch to fix this
  requires:
    - pip

about:
  home: https://pypi.org/project/rembg
  summary: Remove image background
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/danielgatis/rembg

extra:
  recipe-maintainers:
    - danielgatis
    - goanpeca
