{% set name = "rembg" %}
{% set version = "2.0.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rembg-{{ version }}.tar.gz
  sha256: 9604059e09b89da38fe219f5302af2b0a099260146d3ede7957b01e9a9d97d03
  patches:
    - cli.patch

build:
  entry_points:
    - rembg=rembg.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - setuptools >=65.5.1
    - wheel
  run:
    - jsonschema
    - numpy
    - onnxruntime
    - opencv
    - pillow
    - pooch
    - pymatting
    - python >=3.8,<3.12
    - scikit-image        # Not imported
    - scipy
    - tqdm
    # Optional for CLI extras
    - aiohttp
    - asyncer
    - click
    - fastapi
    - filetype
    - gradio
    - python-multipart
    - starlette           # Imported but not in requirements
    - uvicorn
    - watchdog

test:
  imports:
    - cv2
    - rembg
  commands:
    - pip list
    # - pip check  # Fails due to opencv
    - rembg --help  # Added patch to fix this
  requires:
    - pip

about:
  home: https://pypi.org/project/rembg
  summary: Remove image background
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/danielgatis/rembg

extra:
  recipe-maintainers:
    - danielgatis
    - goanpeca
