{% set name = "rembg" %}
{% set version = "2.0.80" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/rembg-{{ version }}.tar.gz
  sha256: 91b82fae42d958d655babe38f9ec018031dbcd658ae8de5b67ce59028e0d1ff3

build:
  entry_points:
    - rembg=rembg.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
  run:
    - jsonschema
    - numpy
    - onnxruntime
    - opencv
    - pillow
    - pooch
    - pymatting
    - python >={{ python_min }},<4.0
    - scikit-image        # Not imported
    - scipy
    - tqdm
    # Optional for CLI extras
    - aiohttp
    - asyncer
    - click
    - fastapi
    - filetype
    - gradio
    - python-multipart
    - starlette           # Imported but not in requirements
    - uvicorn
    - watchdog

test:
  imports:
    - cv2
    - rembg
  commands:
    - pip list
    # - pip check  # Fails due to opencv
    - rembg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/rembg
  summary: Remove image background
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/danielgatis/rembg

extra:
  recipe-maintainers:
    - danielgatis
    - goanpeca
